server:
  port: 8765
spring:
  application:
    name: kredinbizde-gateway
  cloud:
    gateway:
      routes:
        - id: garanti-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/garanti/**
        - id: kredinbizde-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/kredinbizde/**
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    registerWithEureka: false