spring:
  application:
    name: log-service
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/logdb
  kafka:
    consumer:
      auto-offset-reset: latest
      group-id: consumer-group
      bootstrap-servers: kafka:9092
      topic:
        name: log-topic

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://kredinbizde-discovery:8761/eureka