server:
  port: 8082

spring:
  application:
    name: order-service
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672
  main:
    allow-bean-definition-overriding: true
  cloud:
    openfeign:
      client:
        config:
          stock-service:
            url: http://localhost:8084
          product-service:
            url: http://localhost:8083
          customer-service:
            url: http://localhost:8081
          invoice-service:
            url: http://localhost:8085

rabbitmq:
  notification:
    queue: notification.queue
    routing-key: notification.routingkey
  stock:
    queue: stock.queue
    routing-key: stock.routingkey
  invoice:
    queue: invoice.queue
    routing-key: invoice.routingkey
  exchange: patika.exchange


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config