server:
  port: 8080

spring:
  application:
    name: notification-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  notification:
    queue: notification.queue
    routing-key: notification.routingkey
  exchange: patika.exchange
