server:
  port: 8083
spring:
  application:
    name: product-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config