server:
  port: 8081
spring:
  application:
    name: garanti-service

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka # value will get overriden if passed from external config